name: document_saver_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-276.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  file_picker: ^4.6.1
  open_file: ^3.2.1
  dotted_border: ^2.0.0+3
  firebase_database: ^10.0.15
  firebase_storage: ^11.0.15
  intl: ^0.17.0
  syncfusion_flutter_pdfviewer: ^20.4.53
  http: ^0.13.5
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/document.png
    - lib/assets/register.png
    - lib/assets/confusion.png
    - lib/assets/pdf_type.png
    - lib/assets/image_type.png
    - lib/assets/upload.png
    - lib/assets/generic_file.png
    - lib/assets/empty.png
